name: Build Next.js web application

on:
  push:
    branches:
      - main
jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
    - name: Chackout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: kuntalojha/nextwebapp:latest, kuntalojha/nextwebapp:${{github.run_number}}
