name: Bulid Next.js web application
on: push
jobs:
  build-project:
    name: Bulid project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
    - name: Upload static site content
      uses: actions/upload-artifact@v4
      with:
        name: static-site
        path: .next/
  
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Downlode artifact
      uses: actions/download-artifact@v4
      with:
        name: static-site
    - name: Archive site content
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: site.zip